# Generated by Django 6.0.6 on 2026-06-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('uploaded_image', models.ImageField(upload_to='submissions/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.answerkey')),
            ],
        ),
    ]
